# ============================================================
# Grafana Agent Configuration — Sara AI (Fixed for v0.40+)
# ============================================================

server:
  log_level: info
  http:
    listen_address: 0.0.0.0
    listen_port: 12345  # Local port for agent health & metrics

metrics:
  global:
    scrape_interval: 15s
  configs:
    - name: sara-ai
      scrape_configs:
        # ----------------------------------------------------
        # Main Flask API
        # ----------------------------------------------------
        - job_name: sara-ai-core-app
          metrics_path: /metrics
          scheme: https
          static_configs:
            - targets: ['sara-ai-core-app.onrender.com']

        # ----------------------------------------------------
        # Streaming Server
        # ----------------------------------------------------
        - job_name: sara-ai-core-streaming
          metrics_path: /metrics
          scheme: https
          static_configs:
            - targets: ['sara-ai-core-streaming.onrender.com']

      remote_write:
        - url: ${GRAFANA_CLOUD_REMOTE_WRITE_URL}
          basic_auth:
            username: 2725645  # noblecomsolutions stack ID
            password: ${GRAFANA_CLOUD_API_TOKEN}

logs:
  configs:
    - name: sara-ai-logs
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: sara-ai-core-logs
          static_configs:
            - targets: [localhost]
              labels:
                job: sara-ai-core
                __path__: /var/log/*.log
      clients:
        - url: https://logs-prod-006.grafana.net/loki/api/v1/push
          basic_auth:
            username: 2725645
            password: ${GRAFANA_CLOUD_API_TOKEN}
