# ============================================================
# Grafana Agent Configuration — Sara AI
# ============================================================

server:
  log_level: info
  http_listen_port: 12345  # Local port used for agent metrics and health checks

metrics:
  global:
    scrape_interval: 15s
  configs:
    - name: sara-ai
      scrape_configs:
        # ----------------------------------------------------
        # Main Flask API (Prometheus /metrics endpoint)
        # ----------------------------------------------------
        - job_name: sara-ai-core-app
          metrics_path: /metrics
          static_configs:
            - targets: ['sara-ai-core-app.onrender.com']

        # ----------------------------------------------------
        # Streaming Server (Prometheus /metrics endpoint)
        # ----------------------------------------------------
        - job_name: sara-ai-core-streaming
          metrics_path: /metrics
          static_configs:
            - targets: ['sara-ai-core-streaming.onrender.com']

        # ----------------------------------------------------
        # Optional Celery Worker (if exposing port 9102 later)
        # ----------------------------------------------------
        # - job_name: sara-ai-core-worker
        #   metrics_path: /metrics
        #   static_configs:
        #     - targets: ['sara-ai-core-worker.onrender.com:9102']

      # --------------------------------------------------------
      # Remote Write to Grafana Cloud Prometheus
      # --------------------------------------------------------
      remote_write:
        - url: ${GRAFANA_CLOUD_REMOTE_WRITE_URL}
          basic_auth:
            username: 2725645  # <-- Your Grafana Cloud Stack ID (noblecomsolutions)
            password: ${GRAFANA_CLOUD_API_TOKEN}

logs:
  configs:
    - name: sara-ai-logs
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: sara-ai-core-logs
          static_configs:
            - targets: [localhost]
              labels:
                job: sara-ai-core
                __path__: /var/log/*.log
      clients:
        - url: https://logs-prod-006.grafana.net/loki/api/v1/push
          basic_auth:
            username: 2725645
            password: ${GRAFANA_CLOUD_API_TOKEN}
