server:
  log_level: info

metrics:
  global:
    scrape_interval: 60s
  wal_directory: /var/lib/grafana-agent/data

  configs:
    - name: sara-ai
      scrape_configs:
        - job_name: sara-ai
          static_configs:
            - targets: ['localhost:9090']
      remote_write:
        - url: ${env:GRAFANA_CLOUD_REMOTE_WRITE_URL}
          basic_auth:
            username: ${env:GRAFANA_CLOUD_USER}
            password: ${env:GRAFANA_CLOUD_API_KEY}
