version: "3.9"
services:
  web:
    build: .
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:app", "--workers=2", "--log-level=info"]
    ports:
      - "${WEB_PORT:-5000}:5000"
    env_file: .env
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 20s
      timeout: 5s
      retries: 3

  streaming:
    build: .
    command: ["python", "streaming_server.py"]
    ports:
      - "${STREAMING_PORT:-8765}:8765"
    env_file: .env
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/healthz"]
      interval: 20s
      timeout: 5s
      retries: 3

  worker:
    build: .
    command: ["celery", "-A", "tasks", "worker", "-l", "info"]
    env_file: .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  redis-data:
